### ISSUE TITLE
Check the roles

### ISSUE THREAD

**Issue by GermanBluefox** [smaragdschlange/ioBroker.nuki#1]
https://github.com/smaragdschlange/ioBroker.nuki/blob/master/main.js#L156
Should be indicator.lowbat

You can find the States here https://github.com/ioBroker/ioBroker/blob/master/doc/STATE_ROLES.md

What the state is responsible for open and what for unlock?

**Comment by smaragdschlange** [comment]
Thanks for the advice! I will change it.

Actually the state can have the following values and currently is not for controlling the lock:
0 uncalibrated
1 locked
2 unlocking
3 unlocked
4 locking
5 unlatched
6 unlocked (lock ‘n’ go)
7 unlatching
254 motor blocked
255 undefined

However, there will be one or multiple actions for controlling added. The values for actions are:
1 unlock
2 lock
3 unlatch
4 lock ‘n’ go
5 lock ‘n’ go with unlatch
