### ISSUE TITLE
Not starting

### ISSUE THREAD

**Issue by blebbens** [smaragdschlange/ioBroker.nuki#10]
Hi,

After starting the adapter for my bridge, connected to Nuki V2, the log is showing this messages:

instance system.adapter.nuki.0 terminated with code 0 (OK)
by controller[0]: at Request.emit (events.js:211:7)
by controller[0]: at emitOne (events.js:116:13)
by controller[0]: at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1161:10)
by controller[0]: at Request.emit (events.js:214:7)
by controller[0]: at emitTwo (events.js:126:13)
by controller[0]: at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
by controller[0]: at Request._callback (/opt/iobroker/node_modules/iobroker.nuki/main.js:555:21)
by controller[0]: at updateAllLockStates (/opt/iobroker/node_modules/iobroker.nuki/main.js:418:13)
by controller[0]: at initNukiStates (/opt/iobroker/node_modules/iobroker.nuki/main.js:341:5)
by controller[0]: at setLockState (/opt/iobroker/node_modules/iobroker.nuki/main.js:358:23)
by controller[0]: TypeError: Cannot read property 'state' of undefined

I typed in the correct token.

**Comment by smaragdschlange** [comment]
Hi,
which version of the adapter are you using? Did you create the instances of the adapter completely from scratch? Are you running a script that already connects to the Nuki bridge?

**Comment by smaragdschlange** [comment]
Ok, I've encountered the same problem today. The reason for this (at least in my case) is a Nuki lock registered in the bridge but not actually connected to the bridge anymore.
I will try to find a way to catch this event and skip the missing Nuki.
