### ISSUE TITLE
Trigger Events work, but states do not update.

### ISSUE THREAD

**Issue by LuckyTGX** [smaragdschlange/ioBroker.nuki#15]
Hi,

I'm using version 1.0.3 and have the following issue:
- the trigger events work fine but
- the states simply do not change. 

It looks like that:
![image](https://user-images.githubusercontent.com/35341948/52182852-ea26cb00-2801-11e9-8e2e-3282734e9446.png)

The door is locked at the very moment. Still the state is unlocked.
No matter whether I unlock or lock using the trigger events or the button on the door, the states stay the same.

Did I do something wrong?
The log for the nuki-instance is empty.

Thanks in advance for your help!
Best regards,
Robert

**Comment by smaragdschlange** [comment]
Hi there,
did you update from an earlier version? If so, please delete all instances of the adapter and create a new one. Do you use the callback function? Please check the following address in your browser:
http://<nuki bridge ip>:<nuki bridge port>/callback/list?token=<token>
It should show something like this:
`

callbacks |  
-- | --
0 |  
id | 1
url | "http://*iobroker ip*:9092/api/nuki"

`
Also, you could set the instance to debug log level and see whether there's a hint (or post it here).
