### ISSUE TITLE
aktualisiert nicht 

### ISSUE THREAD

**Issue by Ilovegym66** [smaragdschlange/ioBroker.nuki#2]
Hi,
der Adapter funktioniert, spricht mit dem Nuki und holt die Daten einwandfrei ab. 
Allerdings aktualisiert er nicht automatisch.
Er schreibt auch alle Ausgaben in Info, anstatt in debug.

Aber sonst prima gemacht! Hatte das die ganze Zeit mit nem Javascript gelöst.

**Comment by smaragdschlange** [comment]
Hi,
vielen Dank!
Ja, ich hatte leider bisher nicht die Zeit, die Aktualisierung zu implementieren. Ich habe geplant, die aktualisierung durch einen Callback der Nuki Bridge auszulösen, aber ich habe Schwierigkeiten, einen Wegserver zu starten, der den Callback registriert.
Leider hab ich mir wohl beim letzten Versuch was zerschossen, denn der Parameter der IP-Adresse wird nicht mehr gefunden... :-(

P.S.: Dein Javascript hab ich zurzeit behelfsweise auch im Einsatz ;-)

**Comment by Ilovegym66** [comment]
hmm hab jetzt Version 0.0.5, hat von locked auf unlocked ca. 2min gebraucht, um festzustellen, dass unlocked ist.. dann wieder locked.. und das interessiert garnicht..
Habe Callback an, Port 9092 wie in den Voreinstellungen, der Port ist auch erreichbar.

**Comment by smaragdschlange** [comment]
Hi,
Callback ist leider noch work-in-progress, weil ich noch nicht weiß, wie ich den POST parsen kann.
Mit Version 0.0.6 funktioniert der Callbach zwar immer noch nicht, aber die Steuerungaktionen sind verbessert. An den Callback taste ich mich noch heran...

Gruß,
Sven

**Comment by smaragdschlange** [comment]
So, der Nuki Callback funktioniert jetzt soweit. Längere Verzögerungen > 5 Sekunden konnte ich bei mir nicht feststellen.
Ich werde in der nächsten Version noch die Option für ein Abfrageintervall bei der Nuki Bridge mit aufnehmen, damit der Adapter auch ohne Webserver betrieben werden kann und der Status auch aktualisiert wird, wenn mal ein Callback nicht angekommen ist / verarbeitet werden konnte.

Ich hoffe, Deine Probleme mit dem Adapter sind somit beseitigt.

Gruß,
Sven

**Comment by smaragdschlange** [comment]
Dein Kommentar, dass State und StateName nicht zusammenpassen lässt mich vermuten, dass Du ein Update durchgeführt hast, ohne die vorhandene Instanz zu löschen. Mit 0.1.0 hab ich State abgeändert und StateName gelöscht. Bitte lösch alle Instanzen des Nuki-Adapters und erstell eine neue Instanz.
Außerdem sehe ich im Log, dass der Callback nicht angelegt werden kann. Könntest Du bitte prüfen, ob der Callback sich manuell über den Browser anlegen lässt (http://192.168.178.95:8080/callback/add?url=http%3A%2F/192.168.178.41:9092/api/nuki&token=ffff)? Sollte das auch nicht funktionieren, hast Du wohl noch ein Problem mit der Bridge. Hast Du die API auf der Nuki Bridge aktiviert?

Gruß,
Sven

**Comment by Ilovegym66** [comment]
Danke für den Tipp, richtig, ich hatte die alte Instanz nicht gelöscht, sondern nur ein Update drüber installiert. Habe diesmal die Instanz gelöscht, sogar noch den Adapter gelöscht, und dann nochmal von Git geladen und ne Instanz installiert. 
Statename und State stimmt jetzt!
Der Fehler mit den Callbacks kam immer noch, durch den Request direkt im Browser wurde die Fehlermeldung "too many callbacks set" ausgeworfen, was ich mit ("http://192.168.178.95:8080/callback/remove?token=ffffff&id=0") zurücksetzen konnte.
Jetzt funktioniert es!! Danke!
Du könntest dies vielleicht noch als Feature einbauen, ich weiss nicht, bei wieviel Callbacks da Schnuki schluss macht..
