### ISSUE TITLE
Wrong implementation has an impact on other Nuki-connected gateways

### ISSUE THREAD

**Issue by hblaschka** [smaragdschlange/ioBroker.nuki#22]
Hi there,

seems your implementation is buggy and thereby influences the behaviour of the Nuki Bridge when being connected to another device (here: homee Smart Home Gateway).

Seems the bridge sends a HTTP Request to ioBroker, which will not be answered correctly (no status 200 response). These leads to the effect that the bridge keeps on waiting for an answer, which never arrives. And this results in the behaviour described on the homee community starting here:

https://community.hom.ee/t/nuki-sperr-zustand-wird-oft-falsch-angezeigt/23353/11?u=hblaschka

Technical details can be discussed via PM with Tankred (@tankred) or Pascal (@pascal), two of the homee Devs on the homee Community or on the above mentioned thread.

Cross posted on https://github.com/Zefau/ioBroker.nuki2 - same behaviour there.

**Comment by smaragdschlange** [comment]
Hi,
thanks for pointing this out. I've added the required response in version 1.0.7. Since I have no homee gateway I'd appreciate if you (or someone with the mentioned combination of installments) could do some testing.

**Comment by hblaschka** [comment]
Thanks for the fast action, I will ask people on the community to do so, as I currently do not run ioBroker in production....

**Comment by bergjet** [comment]
It's all right now, thank you.
