### ISSUE TITLE
Nuki Opener

### ISSUE THREAD

**Issue by papagei1996** [smaragdschlange/ioBroker.nuki#24]
Habe mir den Nuki Opener für die Hauseingangstür verbaut und natürlich über die bridge gekoppelt. Im Adapter wird der Opener auch angezeigt allerdings in Form eines Zweiten Schlosses. Da dieser aber anders ist als das Schloss funktionieren leider keine der Buttons zum öffnen. Kommt hier zufällig ein Update in dem dieser implementiert wird oder ist der Adapter Ausschließlich für das normale Nuki Schloss gedacht?

**Comment by Ilovegym66** [comment]
schau dir mal die erweiterte Version von dem Adapter an, dieser Unterstützt viel mehr
https://github.com/Zefau/ioBroker.nuki-extended

**Comment by papagei1996** [comment]
super funkt alles damit.
vielen dank!

Gruß Jannik

**Comment by smaragdschlange** [comment]
Hi,
ich besitze leider keinen Nuki Opener, werde aber versuchen, ihn in zukünftigen Versionen zu unterstützen.

**Comment by smaragdschlange** [comment]
Ich denke, mit Version 1.1.0 sollte nun auch der Nuki Opener korrekt angezeigt werden und funktionieren.

Gruß
Sven
