### ISSUE TITLE
Keine Datenpunkte / No DataPoints

### ISSUE THREAD

**Issue by lombardi-zz** [smaragdschlange/ioBroker.nuki#26]
Ich nutze die Software Bridge und habe den Adapter installiert.

IP, Port und token sind eingetragen. Bis auf die Bridge Info werden keine Datenpunkte erstellt.

**Comment by smaragdschlange** [comment]
Hi,
hast Du denn die HTTP-API aktiviert? Gibt es irgendwelche Log-Einträge zum Adapter? Wurde der Callback eingerichtet? Starte die Instanz mal im Debug-Modus und poste die Log-Einträge.
Ich bin leider gerade beruflich unterwegs, werde mir die Sache aber in der 2. Wochenhälfte ansehen.

Gruß
Sven

**Comment by lombardi-zz** [comment]
1. HTTP aktiviert.
2. Node V8.9
3. Version 1.1.0
4. NPM 5.5.1
5. Schau nach wenn du Zeit hast :-)

- 2019-11-04 21:04:11.013 - debug: nuki.0 Bridge list requested: https://api.nuki.io/discover/bridges
- --
- 2019-11-04 21:04:11.013 - info: nuki.0 found additional bridge: 2078879302 (IP: undefined; Port: undefined)
- 2019-11-04 21:04:13.809 - debug: nuki.0 config Nuki bridge name: Nuki bridge
- 2019-11-04 21:04:13.810 - debug: nuki.0 config IP address: 192.168.2.30
- 2019-11-04 21:04:13.810 - debug: nuki.0 config port: 8080
- 2019-11-04 21:04:13.810 - debug: nuki.0 config token: lombnuki
- 2019-11-04 21:04:14.319 - debug: nuki.0 redis pmessage io.*.logging io.system.adapter.admin.1.logging {"val":false,"ack":true,"ts":1572897854317,"q":0,"from":"system.adapter.admin.1","lc":1572897854317}
- 2019-11-04 21:04:14.322 - debug: nuki.0 system.adapter.admin.1: logging false
- 2019-11-04 21:04:14.396 - info: nuki.0 Lock list requested: http://192.168.2.30:8080/list?token=lombnuki
- 2019-11-04 21:04:14.850 - debug: nuki.0 redis pmessage io.*.logging io.system.adapter.admin.1.logging {"val":true,"ack":true,"ts":1572897854848,"q":0,"from":"system.adapter.admin.1","lc":1572897854848}
- 2019-11-04 21:04:14.851 - debug: nuki.0 system.adapter.admin.1: logging true
- 2019-11-04 21:04:17.570 - debug: nuki.0 Callback list requested: http://192.168.2.30:8080/callback/list?&token=XXXXX <- auskommentiert 
- 2019-11-04 21:04:17.570 - info: nuki.0 Callback allready set: http://192.168.2.33:9092/api/nuki
- 2019-11-04 21:04:17.584 - info: nuki.0 Server listening to http://192.168.2.33:9092

**Comment by lombardi-zz** [comment]
Hier nochmal der Result von List. 

{"nukiId":333127345,"name":"Oli","lastKnownState":{"state":1,"stateName":"locked","batteryCritical":false,"timestamp":"2019-11-04T09:21:26-11:00"}}

Da gibt es kein deviceType im json !

          switch(obj.deviceType) {
                case 0:
                    initNukiLockStates(obj);
                    break;
                case 2:
                    initNukiOpenerStates(obj);
                    break;
            }

**Comment by smaragdschlange** [comment]
Hi,
vielen Dank für die Analyse!
Ich habe jetzt in Version 1.1.1 den deviceType als optionale Info. Der Adapter geht jetzt von einem Nuki Lock aus, wenn kein deviceType geliefert wird. Es wäre sehr nett, wenn Du die neue Version mal bei Dir installieren und testen könntest.

Gruß
Sven

**Comment by lombardi-zz** [comment]
Hi.

Sieht auf den ersten Blick gut aus :-)

**Comment by smaragdschlange** [comment]
Hi,

das klingt schon mal gut.
Nochmal dazu, dass bei Dir kein deviceType gesendet wird: Hast Du die neueste App-Version und Nuki Firmware-Version installiert? Laut API-Doku sollte das auch bei Software Bridge gesendet werden...

Wie auch immer, vielen Dank für den Issue :)

Gruß
Sven

**Comment by lombardi-zz** [comment]
Hi, ich nochmal.

Die Value info.deviceType muss noch manuell auf 0 gesetzt werden, sonst schmiert das ganze weg.

**Comment by smaragdschlange** [comment]
Hi,

ok, sorry. Ich hatte bei meinen Tests den Fall nicht. Ich kümmere mich darum, sobald ich kann,

Gruß
Sven

**Comment by lombardi-zz** [comment]
Kein Stress, konnte es ja lösen 😊.

Es geht mehr darum dass der nächste der installiert nicht auch das Problem hat.



Mit freundlichem Gruß

Oliver Lombardi
Am 7. Nov. 2019, 06:59 +0100 schrieb Smaragdschlange <notifications@github.com>:

**Comment by smaragdschlange** [comment]
Eine Frage noch: Hattest Du die Objekte gelöscht, bevor Du den Adapter aktualisiert hast? Wenn nicht, würde das erklären, warum der Default-Wert (0) nicht gesetzt wurde.

**Comment by smaragdschlange** [comment]
So, Version 1.1.2 sollte nun auch den deviceType auf jeden Fall updaten, sodass ein valider Wert drinsteht. Außerdem wird bei Statusabfragen jetzt ganz davon abgesehen, den deviceType mitzugeben, wenn er nicht gepflegt ist.
Danke nochmal für's Testen.

Gruß
Sven
