### ISSUE TITLE
Neue Version?

### ISSUE THREAD

**Issue by ZeroQool007** [smaragdschlange/ioBroker.nuki#27]
Hallo, kann es sein, dass die neue Versio nicht getaggt ist? Kann über iobroker & co nur Version 1.0.7 installieren. Danke

**Comment by smaragdschlange** [comment]
Hi,
1.0.7 ist die letzte Stable-Version...
Hast Du als aktiven Verwahrungsort in ioBroker "latest" oder "default" stehen. Die neueste Version (1.1.2) wird erst demnächst als stable-Version deklariert werden. Kannst Du die neueste Version nicht sehen, oder bekommst Du einen Fehler bei der Installation? (...und welches System ist unter "& co" zu verstehen?)

**Comment by ZeroQool007** [comment]
Hi, auf DEFAULT. Ok, wieder was dazugelernt. Ich dank dir, funktioniert nun. Gruß
