### ISSUE TITLE
action 1 not successfully set!

### ISSUE THREAD

**Issue by stenmic** [smaragdschlange/ioBroker.nuki#29]
ich bekomme oft Warnungen im Log das eine Aktion nicht gesetzt werden konnte z.B. action 1 not successfully set!.
Jedoch wurde diese Aktion dann ohne Probleme durchgeführt.
Ich nutze die Version 1.1.2

**Comment by smaragdschlange** [comment]
Hi,
kannst Du bitte mal das Log posten? Wie ist denn Deine Konfiguration (Lock, Opener, Türsensor, Harware- Softwarebridge)?

**Comment by smaragdschlange** [comment]
Hallo,
könntest Du bitte mal die Version 1.1.3 hier von GitHub installieren und testen? Ich hab ja leider keinen Opener...

Vielen Dank.

Gruß Sven
