### ISSUE TITLE
function to open/lock door

### ISSUE THREAD

**Issue by Ilovegym66** [smaragdschlange/ioBroker.nuki#3]
Hi,
it's possible to implement a function that sends a http-request to the bridge, that the door can be locked or opened? 
the request is like this:

http://IP:8080/lockAction?&nukiId=NukiID&Action=3&token=bridgetoken

**Comment by smaragdschlange** [comment]
Hi there,
I'm afraid this adapter is far from being usefull. Actually I know the API of the Nuki and I use it already in other systems (like openHAB and Homematic/CuxD) but I didn't get to implement this to the adapter, yet.
I will try to add functionality to the adapter, but my time *and experience in adapter development* is limited.

**Comment by smaragdschlange** [comment]
Hi,
I've added an input parameter for sending lock actions. The adapter can be used now :-)
