### ISSUE TITLE
Version 1.1.3 

### ISSUE THREAD

**Issue by Ilovegym66** [smaragdschlange/ioBroker.nuki#32]
Hi, with V1.1.3 from today follow fault comes up:
`

nuki.0 | 2020-03-06 16:13:17.959 | info | (25565) Callback successfully set: http://192.168.178.41:11111/api/nuki.0
-- | -- | -- | --
nuki.0 | 2020-03-06 16:13:15.454 | info | (25565) Bridge Info requested: http://192.168.178.93:8080/info?token=geheim
nuki.0 | 2020-03-06 16:13:14.224 | info | (25565) Server listening to http://192.168.178.41:11111
nuki.0 | 2020-03-06 16:13:12.065 | info | (25565) Lock list requested: http://192.168.178.93:8080/list?token=geheim
nuki.0 | 2020-03-06 16:13:11.092 | info | (25565) found hardware bridge: 164400993 (IP: 192.168.178.93; Port: 8080)
nuki.0 | 2020-03-06 16:13:04.962 | info | (25565) starting. Version 1.1.3 in /opt/iobroker/node_modules/iobroker.nuki, node: v10.19.0
nuki.0 | 2020-03-06 16:12:32.776 | info | (25388) Callback-ID successfully removed: 0
nuki.0 | 2020-03-06 16:12:32.691 | info | (25388) Terminated (NO_ERROR): Without reason
nuki.0 | 2020-03-06 16:12:32.674 | info | (25388) terminating
nuki.0 | 2020-03-06 16:12:32.655 | info | (25388) cleaned everything up...
nuki.0 | 2020-03-06 16:12:32.651 | error | at IncomingMessage.emit (events.js:203:15)
nuki.0 | 2020-03-06 16:12:32.651 | error | at Object.onceWrapper (events.js:286:20)
nuki.0 | 2020-03-06 16:12:32.651 | error | at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/request/request.js:1083:12)
nuki.0 | 2020-03-06 16:12:32.651 | error | at Request.emit (events.js:198:13)
nuki.0 | 2020-03-06 16:12:32.651 | error | at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1161:10)
nuki.0 | 2020-03-06 16:12:32.651 | error | at Request.emit (events.js:198:13)
nuki.0 | 2020-03-06 16:12:32.651 | error | at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
nuki.0 | 2020-03-06 16:12:32.651 | error | at Request._callback (/opt/iobroker/node_modules/iobroker.nuki/main.js:1036:21)
nuki.0 | 2020-03-06 16:12:32.651 | error | at updateAllLockStates (/opt/iobroker/node_modules/iobroker.nuki/main.js:791:13)
nuki.0 | 2020-03-06 16:12:32.651 | error | at setLockState (/opt/iobroker/node_modules/iobroker.nuki/main.js:757:26)
nuki.0 | 2020-03-06 16:12:32.651 | error | (25388) ReferenceError: _obj is not defined
nuki.0 | 2020-03-06 16:12:32.651 | error | (25388) uncaught exception: _obj is not defined
nuki.0 | 2020-03-06 16:12:32.644 | info | (25388) Lock list requested: http://192.168.178.93:8080/list?token=geheim
nuki.0 | 2020-03-06 16:11:39.625 | info | (25388) Bridge Info requested: http://192.168.178.93:8080/info?token=geheim
nuki.0 | 2020-03-06 16:11:38.690 | info | (25388) Server listening to http://192.168.178.41:11111
nuki.0 | 2020-03-06 16:11:38.685 | info | (25388) Callback allready set: http://192.168.178.41:11111/api/nuki.0
nuki.0 | 2020-03-06 16:11:36.414 | info | (25388) Lock list requested: http://192.168.178.93:8080/list?token=geheim
nuki.0 | 2020-03-06 16:11:35.601 | info | (25388) found hardware bridge: 164400993 (IP: 192.168.178.93; Port: 8080)
nuki.0 | 2020-03-06 16:11:29.479 | info | (25388) starting. Version 1.1.3 in /opt/iobroker/node_modules/iobroker.nuki, node: v10.19.0
nuki.0 | 2020-03-06 16:10:57.567 | error | (25087) null
nuki.0 | 2020-03-06 16:10:57.160 | info | (25087) Terminated (NO_ERROR): Without reason

`

**Comment by Speedbreaker12** [comment]
I can confirm. Same thing for me.

**Comment by smaragdschlange** [comment]
Hi,
thanks for reporting. 
I've fixed it in Version 1.1.4. Please install from GitHub and test.

Regards
Sven

**Comment by Speedbreaker12** [comment]
> 
> 
> Hi,
> thanks for reporting.
> I've fixed it in Version 1.1.4. Please install from GitHub and test.
> 
> Regards
> Sven

Thank you very much for the quick fix! Works great for me.

**Comment by Ilovegym66** [comment]
verified, fixed in 1.1.4. thank you very much!
