### ISSUE TITLE
Unknown device type (1). Setting minimal states.

### ISSUE THREAD

**Issue by DcFamas** [smaragdschlange/ioBroker.nuki#33]
Hey there,
I recently installed the adapter in ioBroker.
Installed the bridge on my old Galaxy A3 (2017), configured it to connect it with ioBroker.

Everything works like a charme, but the adapter tells me in the log

`

nuki.0 | 2020-04-11 20:48:02.338 | error | (9769) Unknown device type (1). Setting minimal states.
-- | -- | -- | --
nuki.0 | 2020-04-11 20:48:02.335 | info | (9769) Lock list requested: http://192.168.178.44:8080/list?token="token"
nuki.0 | 2020-04-11 20:47:59.381 | info | (9769) Bridge Info requested: http://192.168.178.44:8080/info?token="token"
nuki.0 | 2020-04-11 20:47:56.165 | info | (9769) starting. Version 1.2.0 in /opt/iobroker/node_modules/iobroker.nuki, node: v10.19.0
host.ioBroker | 2020-04-11 20:47:53.753 | info | instance system.adapter.nuki.0 started with pid 9769
host.ioBroker | 2020-04-11 20:47:53.738 | info | "system.adapter.nuki.0" enabled

`

The nuki bridge app says, that everything is fine with three green dots.

Thank you for your support and best regards! :)

**Comment by smaragdschlange** [comment]
Hi @DcFamas ,
I suppose that you replaced the real token by the word "token" in the log, right?
Could you please try to start the adapter in debug mode and send the log? And please tell me the app version you're using.

Thanks.

**Comment by DcFamas** [comment]
Hey @smaragdschlange,
yes i replaced it. When the token is wrong, I get the log that the token is wrong.

The App Version is 1.4.6, the play store does not offer me a newer one.

`

nuki.0 | 2020-04-12 11:31:15.950 | debug | (31579) Callback list requested: http://192.168.178.44:8080/callback/list?&token=mytoken
-- | -- | -- | --
nuki.0 | 2020-04-12 11:31:12.897 | debug | (31579)  stateChange nuki.0.449585013.info.batteryCritical  {"val":false,"ack":true,"ts":1586683872891,"q":0,"from":"system.adapter.nuki.0","user":"system.user.admin","lc":1586629887429}
nuki.0 | 2020-04-12 11:31:12.884 | error | (31579) Unknown device type (1). Setting minimal states.
nuki.0 | 2020-04-12 11:31:12.882 | debug | (31579) found Nuki device: 449585013
nuki.0 | 2020-04-12 11:31:12.881 | info | (31579) Lock list requested: http://192.168.178.44:8080/list?token=mytoken
nuki.0 | 2020-04-12 11:31:09.937 | info | (31579) Bridge Info requested: http://192.168.178.44:8080/info?token=mytoken
nuki.0 | 2020-04-12 11:31:06.775 | debug | (31579) config token: mytoken
nuki.0 | 2020-04-12 11:31:06.775 | debug | (31579) config port: 8080
nuki.0 | 2020-04-12 11:31:06.775 | debug | (31579) config IP address: 192.168.178.44
nuki.0 | 2020-04-12 11:31:06.774 | debug | (31579) config Nuki bridge name: Nuki bridge
nuki.0 | 2020-04-12 11:31:06.738 | info | (31579) starting. Version 1.2.0 in /opt/iobroker/node_modules/iobroker.nuki, node: v10.19.0
nuki.0 | 2020-04-12 11:31:06.051 | debug | (31579) statesDB connected
nuki.0 | 2020-04-12 11:31:06.050 | debug | (31579) States connected to redis: 127.0.0.1:9000
nuki.0 | 2020-04-12 11:31:06.039 | debug | (31579) States create System PubSub Client
nuki.0 | 2020-04-12 11:31:06.037 | debug | (31579) States create User PubSub Client
nuki.0 | 2020-04-12 11:31:06.029 | debug | (31579) Redis States: Use Redis connection: 127.0.0.1:9000
nuki.0 | 2020-04-12 11:31:06.026 | debug | (31579) objectDB connected
nuki.0 | 2020-04-12 11:31:06.018 | debug | (31579) Objects connected to redis: 127.0.0.1:9001
nuki.0 | 2020-04-12 11:31:06.004 | debug | (31579) Objects client initialize lua scripts
nuki.0 | 2020-04-12 11:31:06.003 | debug | (31579) Objects create User PubSub Client
nuki.0 | 2020-04-12 11:31:06.002 | debug | (31579) Objects create System PubSub Client
nuki.0 | 2020-04-12 11:31:05.996 | debug | (31579) Objects client ready ... initialize now
nuki.0 | 2020-04-12 11:31:05.951 | debug | (31579) Redis Objects: Use Redis connection: 127.0.0.1:9001
host.ioBroker | 2020-04-12 11:31:04.465 | info | instance system.adapter.nuki.0 started with pid 31579

`

**Comment by smaragdschlange** [comment]
Hi @DcFamas ,
thank you for your reply.
I think I figured out the problem. Although it is never mentioned in the API documentation, the software bridge doesn't send the device type. I could just default to device type 0 (Nuki lock) but since it's possible to run an opener with a software bridge I'd like to try and implement an additional approach to determine the device type. This might take some time...
In the meantime you could use the new adapter version 1.2.1 from GitHub. It'll fix your problem.

Regards
Sven

**Comment by DcFamas** [comment]
Hey @smaragdschlange 
thanks for the explonation. :)
Please don't stress yourself, I can wait. Maybe it is enough that the user choose for himself which device he uses?

Best regards René

**Comment by smaragdschlange** [comment]
Hi again,
I've created version 1.2.2 now. If not provided by the bridge, the adapter is now able to figure out the device type by state name (works if state is not "undefined").
Please let me know if this works for you.

Regards
Sven

**Comment by DcFamas** [comment]
Hey @smaragdschlange 
sorry for the late answer. Work is a little bit exhausting at this time.

It works for me, everything is fantastic now. :)

Thank you for your time and keep up the excellent work!

Best regards René
