### ISSUE TITLE
Possible to show door is opened? (not unlocked, really open by the extra sensor?)

### ISSUE THREAD

**Issue by Koalabaer** [smaragdschlange/ioBroker.nuki#35]
Hello, 

would it be possible to get the state when the door is really open. Currently it shows only locked and unlocked.

BR and thanks

Koala

**Comment by smaragdschlange** [comment]
Hi Koala,
at this point, there's no way of getting the "door open" state from the bridge. The adapter is based on the current version of the Nuki bridge API which doesn't support this information.
I hope that in future firmware updates the lock states will be replenished. In this case I will add the state to the adapter.
Regards
Sven
