### ISSUE TITLE
Updated to 1.10.0, false battery indication

### ISSUE THREAD

**Issue by WolfgangN57** [smaragdschlange/ioBroker.nuki#40]
Hi there, a few days ago I updated the nuki to 1.10.0, yesterday I got in datapoint batteryCritical the value "true", therefore I changed batteries to new ones, but still have the value "true", also it showes 1.9.5 as the firmwareVersion. In the official nuki-app batteries are ok and firmware is correctly shown as 1.10.0
Any Idea?

Regards
Wolfgang

**Comment by smaragdschlange** [comment]
Hi Wolfgang,
can you please tell me the version of Nuki adapter you're using? Also, are you using the callback funktion? What's the value in data point "timestamp", and is the current status of the Nuki (locked, unlocked) being updated when you lock or unlock it?
I'm going to look into this issue as soon as I have some spare time, but workload on my day job is crazy these days ...

Regards Sven

**Comment by WolfgangN57** [comment]
Hi Sven,

adapter version is 1.3.0, no callback used, timestamp is correct with the last state-change, states are updated as well. I can also use a button/switch to change the state remotely. Everything works fine, only the batteryCritical and firmwareVersion states are incorrect.

Next time in deutsch?

Grüße

Wolfgang

Von meinem iPad gesendet

**Comment by smaragdschlange** [comment]
Hallo Wolfgang,
ich seh mir den Fall an, hab aber zwischen Arbeit und Familie kaum Zeit... 
Darf ich mal fragen, warum Du den Callback nicht benutzt?

Gruß 
Sven

**Comment by WolfgangN57** [comment]
Hi Sven,

bei iobroker bin ich noch neu und erst seit wenigen Wochen dabei, macht aber viel Spaß. Ich nutze mittlerweile sehr viele Adapter zuhause. Callback nutz ich nicht, da ich dessen Funktion  nicht kenne und für was ich es nutzen kann. Ansonsten funzt ja alles mit Nuki. Vllt kannst du mir das ja erklären.

Grüße

Wolfgang

Von meinem iPad gesendet

**Comment by smaragdschlange** [comment]
Hi,
gern. Der Callback ist sehr praktisch, da die Nuki Bridge damit  direkt eine Statusänderung an den ioBroker sendet, wenn sich was geändert hat (z.B. Tür wird manuell abgeschlossen). Die Intervall-Abfrage des Status im Adapter ist nur eine Krücke für den Fall, dass man z.B. keinen Callback einrichten kann, weil man mehr als 3 Bridges hat.
Was Du über den Batteriestatus meldest ist offenbar ein Fehler (der sich wohl auch auf die Anzeige der Firmware auswirkt. Ich muss mich da durch Testen herantasten, um zu sehen, wie das zustande kommt.
Ich denke aber, dass Du in der Zwischenzeit folgendes machen kannst:
1. versuche, den Callback einzusetzen
2. Lösche alle Datenpunkte und starte den Adapter neu

Gruß
Sven

**Comment by WolfgangN57** [comment]
Hi Sven,

habe den Adapter gestoppt,  batteryCritical und firmwareVersion gelöscht und den Adapter neu gestartet. Jetzt wird die korrekte Firmware mit 1.10.0 angezeigt, batteryCritical ist aber noch true. Da die Batterie ja nur alle 15min abgefragt wird, ändert sich das vllt noch. Callback habe ich aktiviert.

Grüße

Wolfgang

Von meinem iPad gesendet

**Comment by smaragdschlange** [comment]
Hi,
mit der aktuellen Version sollte das Problem eigentlich behoben sein. Bei mir wird jedenfalls Batteriestatus und Firmwareversion korrekt aktualisiert. Solltest Du noch immer nicht den korrekten Batteriestatus angezeigt bekommen, installiere bitte Version 1.3.1 direkt von GitHub.
In jedem Fall wäre es nett, wenn Du mir noch mal eine Rückmeldung geben könntest.

Gruß
Sven

**Comment by WolfgangN57** [comment]
Hi Sven, mach ich Montag, bin gerade unterwegs.
Grüße 
W

Von meinem iPhone gesendet

**Comment by WolfgangN57** [comment]
Hi Sven,

habe jetzt von unterwegs über github die version 1.3.1 geladen, nochmals die beiden Datenpunkte gelöscht und den Adapter neu geladen. Wieder ist die batteryCritical auf true und im Widerspruch zur nuki-app, da sind die Batterien als ausreichend geladen angezeigt, die version wird korrekt angezeigt.

Grüße

W



Von meinem iPad gesendet

**Comment by Ilovegym66** [comment]
Bei mir funktioniert die battery critical Anzeige einwandfrei. Nuki Adapter 1.3.1 und nuki Lock Version 1.9.6

**Comment by WolfgangN57** [comment]
Hatt bei mir mit 1.9.6 ebenfalls funktioniert, nach dem update auf 1.10.0 eben nicht mehr, der Rest funzt ja.

W

 

Von: Ilovegym66 [mailto:notifications@github.com] 
Gesendet: Samstag, 29. August 2020 14:49
An: smaragdschlange/ioBroker.nuki <ioBroker.nuki@noreply.github.com>
Cc: WolfgangN57 <wnitzschke@web.de>; Author <author@noreply.github.com>
Betreff: Re: [smaragdschlange/ioBroker.nuki] Updated to 1.10.0, false battery indication (#40)

 

Bei mir funktioniert die battery critical Anzeige einwandfrei. Nuki Adapter 1.3.1 und nuki Lock Version 1.9.6

**Comment by smaragdschlange** [comment]
Hm, dann muss ich wohl mein altes Nuki 1 wiedrr aktivieren und updaten...vieleicht gibt es ja eine undokumentierte Änderung in der AO

**Comment by WolfgangN57** [comment]
Da wäre ich dir sehr dankbar
W

Von meinem iPad gesendet

**Comment by smaragdschlange** [comment]
Hi Wolfgang,
ich hatte noch nicht die Zeit, selbst zu testen, aber ich habe zur Firmware 1.10.0 Folgendes gefunden:
[https://developer.nuki.io/t/smart-lock-1-0-firmware-1-10-x-beta/6793](url)
Das könnte natürlich Dein Problem erklären. Ich will sehen, ob ich das mit dem Adapter abfangen kann.

Gruß Sven

**Comment by smaragdschlange** [comment]
Hi,
ich hatte heute Gelegenheit, mir die Sache etwas näher anzusehen. Leider muss ich Dir mitteilen, dass ich nicht vorhabe, mich für das Nuki Beta-Testprogramm einzuschreiben, um mit diesem Adapter experimentelle Features zu unterstützen. Ich verstehe, wenn man alle Features sofort nutzen möchte, sobald diese veröffentlicht werden, aber es gibt gute Gründe, Alpha- und Beta-Versionen bei der Adapterentwicklung außen vor zu lassen. 
Meine Empfehlung an Dich ist, zurück zur offiziellen Stable Version 1.9.6 der Nuki FW zu gehen, wenn Du diesen Adapter fehlerfrei nutzen möchtest.
Sobald Nuki die neuen Funktionen in ihrer offiziellen FW-Version ausliefern und in ihrer API-Doku beschreiben, werde ich versuchen, diese auch in den Adapter einzubauen. 

Gruß Sven

**Comment by WolfgangN57** [comment]
Hi Sven, ich bin kein Beta-Tester, da muss wohl was falsch hinterlegt sein bei Nuki. Weißt du, wie ich auf die 1.9.6 zurückkehren kann?

Grüße 

Wolfgang

Von meinem iPhone gesendet

**Comment by smaragdschlange** [comment]
Hi,
da kann Dir bestimmt der Nuki-Support weiterhelfen. Ich weiß es leider
nicht.

Gruß Sven

WolfgangN57 <notifications@github.com> schrieb am Sa., 5. Sep. 2020, 12:15:

**Comment by WolfgangN57** [comment]
Hi Sven, ein downgrade geht leider nicht, man hat mich aner aus der beta genommen und....
seit heute ist der batteryCritical status wieder auf false, warum weiß der Himmel.
Grüße 
Wolfgang

Von meinem iPhone gesendet

**Comment by smaragdschlange** [comment]
Hi Wolfgang,
naja, wird ja dann kein Dauerzustand mit der Beta sein, wenn Du aus der
Liste raus bist. Vielen Dank für Dein Update.

Gruß Sven

WolfgangN57 <notifications@github.com> schrieb am So., 13. Sep. 2020, 16:09:
