### ISSUE TITLE
adapter startet nach aktualisierung auf 1.4.0 nicht mehr

### ISSUE THREAD

**Issue by JackDaniel007** [smaragdschlange/ioBroker.nuki#41]
nuki.0 | 2020-11-05 13:15:14.027 | error | (3283) ReferenceError: _obj is not defined at initNukiOpenerStates (/opt/iobroker/node_modules/iobroker.nuki/main.js:576:5) at initNukiDeviceStates (/opt/iobroker/node_modules/iobroker.nuki/ma
-- | -- | -- | --
nuki.0 | 2020-11-05 13:15:14.026 | error | (3283) uncaught exception: _obj is not defined

**Comment by smaragdschlange** [comment]
Hi,
strange...I wonder why this error didn't show on my installation.
I'm on it.

Regards
Sven

**Comment by smaragdschlange** [comment]
Ich hab jetzt Version 1.4.1 in GitHub hochgeladen. Könntest Du bitte diese Version mal installieren und sehen, ob Du noch irgendwelche Fehler bekommst?

Vielen Dank.

Gruß
Sven

**Comment by JackDaniel007** [comment]
danke für die rasche hilfe, mit der 1.4.1 geht´s nun wieder wie es soll :)
