### ISSUE TITLE
Bridge Name

### ISSUE THREAD

**Issue by AndiEss71** [smaragdschlange/ioBroker.nuki#5]
Hallo!

Ersteinmal vielen Dank für Deine Arbeit.

Wie bekomme ich den Namen meiner Bridge raus (um ihn in die Adapterkonfiguration einzutragen)?
IP-Adresse, Token und Port sind schon eingetragen, der Adapter wird bloss nicht grün.

Cheers,
Andi

**Comment by smaragdschlange** [comment]
Hi,
der Name ist eigentlich unwichtig und dient nur der besseren Übersicht (darum ist er auch schon vorbelegt). Wenn man dort nichts einträgt, wird er aus der IP-Adresse generiert.
Gibt es Log-Einträge zum Nuki? Wäre gut, wenn Du das Log mal herunterlädtst kurz nachdem Du die Instanz neu gestertet hast und es dann hier postest.

Gruß,
Sven

**Comment by AndiEss71** [comment]
Hi Sven,

vielen Dank für die Antwort.

Hier das log.

host.raspberrypi | 2018-09-02 11:41:04.259 | info | Do not restart adapter system.adapter.nuki.0 because disabled or deleted
-- | -- | -- | --
host.raspberrypi | 2018-09-02 11:41:04.258 | error | instance system.adapter.nuki.0 terminated with code 1 ()
yahka.0 | 2018-09-02 11:40:53.342 | info | objectChange system.adapter.nuki.0 {'_id':'system.adapter.nuki.0','type':'instance','common':{'name':'nuki','version':'0.0.4','news':{'0.0.1':{'en':'initial adapter','de':'Initiale Version'},'0.0.2':{'en':'added input parameters','de':'Eingabeparameter hinzugefügt'},'0.0.3':{'en':'bug fixes and restructure','de':'Fehlerbehebung und Restruktuierung'},'0.0.4':{'en':'added input parameter for lock actions','de':'Eingabeparameter für Lock-Aktion hinzugefügt'}},'title':'Nuki adapter','titleLang':{'en':'Nuki Smart Lock adapter','de':'Nuki Smart Lock Adapter'},'desc':{'en':'This adapter allows to control and monitor the Nuki Smart Lock','de':'Dieser Adapter ermöglicht die Steuerung und Überwachung des Nuki Smart Lock'},'authors':['smaragdschlange '],'docs':{'en':'docs/en/admin.md','de':'docs/de/admin.md'},'platform':'Javascript/Node.js','mode':'daemon','icon':'nuki-logo.png','materialize':true,'enabled':false,'extIcon':'https://raw.githubusercontent.com/smaragdschlange/ioBroker.nuki/master/admin/nuki-logo.png','keywords':['nuki','smart','lock'],'readme':'https://github.com/smaragdschlange/ioBroker.nuki/blob/master/README.md','loglevel':'info','type':'hardware','restartAdapters':['vis'],'installedVersion':'0.0.4','host':'raspberrypi'},'native':{'bridge_name':'Nuki bridge','bridge_ip':'192.168.178.93','bridge_port':'8080','token':'Vk8PEd','host_cb':false,'host_port':''},'from':'system.adapter.admin.0','ts':1535881253324,'acl':{'object':1636,'owner':'system.user.admin','ownerGroup':'system.group.administrator'}}
host.raspberrypi | 2018-09-02 11:40:53.331 | info | object change system.adapter.nuki.0
host.raspberrypi | 2018-09-02 11:40:33.799 | info | Restart adapter system.adapter.nuki.0 because enabled
host.raspberrypi | 2018-09-02 11:40:33.798 | error | instance system.adapter.nuki.0 terminated with code 1 ()
yahka.0 | 2018-09-02 11:40:33.416 | info | objectChange system.adapter.nuki.0 {'_id':'system.adapter.nuki.0','type':'instance','common':{'name':'nuki','version':'0.0.4','news':{'0.0.1':{'en':'initial adapter','de':'Initiale Version'},'0.0.2':{'en':'added input parameters','de':'Eingabeparameter hinzugefügt'},'0.0.3':{'en':'bug fixes and restructure','de':'Fehlerbehebung und Restruktuierung'},'0.0.4':{'en':'added input parameter for lock actions','de':'Eingabeparameter für Lock-Aktion hinzugefügt'}},'title':'Nuki adapter','titleLang':{'en':'Nuki Smart Lock adapter','de':'Nuki Smart Lock Adapter'},'desc':{'en':'This adapter allows to control and monitor the Nuki Smart Lock','de':'Dieser Adapter ermöglicht die Steuerung und Überwachung des Nuki Smart Lock'},'authors':['smaragdschlange '],'docs':{'en':'docs/en/admin.md','de':'docs/de/admin.md'},'platform':'Javascript/Node.js','mode':'daemon','icon':'nuki-logo.png','materialize':true,'enabled':true,'extIcon':'https://raw.githubusercontent.com/smaragdschlange/ioBroker.nuki/master/admin/nuki-logo.png','keywords':['nuki','smart','lock'],'readme':'https://github.com/smaragdschlange/ioBroker.nuki/blob/master/README.md','loglevel':'info','type':'hardware','restartAdapters':['vis'],'installedVersion':'0.0.4','host':'raspberrypi'},'native':{'bridge_name':'Nuki bridge','bridge_ip':'192.168.178.93','bridge_port':'8080','token':'Vk8PEd','host_cb':false,'host_port':''},'from':'system.adapter.admin.0','ts':1535881233313,'acl':{'object':1636,'owner':'system.user.admin','ownerGroup':'system.group.administrator'}}
host.raspberrypi | 2018-09-02 11:40:33.367 | info | instance system.adapter.nuki.0 started with pid 6756

PS: Token und IP Adresse stimmen definitiv, ich hab das über die Web-API gecheckt.
PPS: Kann es daran liegen, dass ich noch Node 4.7.2 laufen habe?

Vielen Dank für die Mühe,
schöne Grüße,

Andi

**Comment by AndiEss71** [comment]
Hallo Sven,

ich versuch erstmal die Node-Version upzugraden.

Vielen Dank erstmal,

Andi

**Comment by AndiEss71** [comment]
...Node-Upgrade hat geklappt. Adapter läuft!

PS: Node ver 8.11.4

**Comment by smaragdschlange** [comment]
Hi Andi,
schon zu hören, dass es bei Dir funktioniert :-)
Ich werde die Node-Version wohl am Besten in die Dependencies mit aufnehmen.
Der Adapter ist immer noch in Arbeit (der Callback funktioniert z.B. noch nicht), aber die Steuerung des Nuki sollte klappen.

Gruß,
Sven
