### ISSUE TITLE
Wie steuere ich das Nuki Smart Lock in blockly

### ISSUE THREAD

**Issue by mdaudi1982** [smaragdschlange/ioBroker.nuki#51]
Hallo,

Ich habe den Adapter erfolgreich installiert und die Bridge eingebunden. In den Objekten kann ich den Zustand des Smart Locks lesen aber ich bekomme es nicht hin, den Wert zu ändern, sodass sich das Lock öffnet oder schließt. Bei mir z.B. in Verbindung des Zustandes der Terrassentür. Im Log erhalte ich ständig folgenden Error egal ob ich es mit der steuern, umschalten oder aktualisieren Funktion versuche:

javascript.0 | 2021-07-05 22:42:34.461 | error | Error by subscription: empty ID defined. All states matched.
javascript.0 | 2021-07-05 22:42:34.460 | error | Error by subscription: empty ID defined. All states matched.

Bitte um Hilfe.

Gruß,
Micha

**Comment by smaragdschlange** [comment]
Hallo Micha,
ich benutze den Adapter selbst mit zwei Blocklys und habe kein Problem feststellen können. Hier Bilder meiner Blocklys:
Nuki öffnen, wenn Fingerabdruck erkannt:
![grafik](https://user-images.githubusercontent.com/39487634/124548120-8e772680-de2d-11eb-8fbe-d53b6b8909cc.png)

Nuki schließen, wenn anderer Fingerabdruck erkannt:
![grafik](https://user-images.githubusercontent.com/39487634/124548240-bcf50180-de2d-11eb-9100-403813a9bc61.png)

Vielleicht hilft Dir das ja schon. Ansonsten kannst Du mir mal ein Bild von Deinem Blockly und/oder das Coding in dem Skript, das Du verwendest, posten.

Gruß Sven

**Comment by mdaudi1982** [comment]
Hallo Sven,

Was ist "Aktion" für eine Objekt ID bei dir? Ich verwende wie in der Anleitung diese hier:

lockAction: Switch for locking / unlocking the Nuki (true = unlock; false = lock)

Ist das nicht richtig? Hier mein Blockly:

![Blockly](https://user-images.githubusercontent.com/82971021/124554091-da2dce00-de35-11eb-9b4e-33c63cf6aeeb.jpg)

und log:

![Log](https://user-images.githubusercontent.com/82971021/124554110-e1ed7280-de35-11eb-96a7-abe1efe2c0e5.jpg)

Gruß,
Micha

**Comment by mdaudi1982** [comment]
Ok,

Erst gucken, dann fragen... ;) die "action" ist die Objekt ID darüber. Werde es umbauen und ausprobieren.

**Comment by smaragdschlange** [comment]
Ich denke aber, Dein Problem liegt eher in dem Falls-Teil. Ich habe nun einfach mal Folgendes in ein neues Skript gepackt und es ausgeführt. Es funktioniert bei mir:
![grafik](https://user-images.githubusercontent.com/39487634/124556251-588b6f80-de38-11eb-9dd0-1a45540a0057.png)

Gruß Sven

**Comment by mdaudi1982** [comment]
Und ich habe gerade dein Skript ausprobiert und es funktioniert ebenfalls wunderbar.
Aber was könnte an dem Falls Baustein falsch sein? 
Die Idee ist eigentlich, wenn Schiebetür im Esszimmer oder im Schlafzimmer offen sind, dann soll das Nuki Schloss öffnen.
Wenn beide zu sind, soll es wieder schließen.
Ein Idee wie ich es sonst bauen könnte?
Danke dir für die Hilfe!

**Comment by smaragdschlange** [comment]
Versuchs mal so:
![grafik](https://user-images.githubusercontent.com/39487634/124556966-3cd49900-de39-11eb-81da-45b7fb4bd828.png)

**Comment by mdaudi1982** [comment]
Genau, so hatte ich es bereits probiert. Funktioniert einwandfrei.

Nun kommt aber noch eine Oder Verknüpfung. Die dann so aussehen könnte aber leider nicht funktioniert:

![Blockly](https://user-images.githubusercontent.com/82971021/124557835-3b57a080-de3a-11eb-9a7f-66d78f1ecfda.jpg)

Das war das eigentliche Anfangsskript. Zumindest weiß ich jetzt, dass ich das Nuki Lock schalten kann, super wäre jetzt nur noch in Abhängigkeit von der Bedingung.

**Comment by mdaudi1982** [comment]
Abgesehen davon, dass ich natürlich das Objekt lockAction benutzt hatte, aber das funktioniert ja ebenfalls, wie wir gerade festgestellt haben.

**Comment by smaragdschlange** [comment]
So sollte es klappen:
![grafik](https://user-images.githubusercontent.com/39487634/124558443-e8321d80-de3a-11eb-9907-b32a8a2c296d.png)

**Comment by mdaudi1982** [comment]
Wir kommen der Sache nahe... Nur die der Block "Objekt ID" ist ja ein fester Trigger... Dem kann ich kein Objekt zuweisen.
Woher weiß das Skript jetzt, wann die Schiebetüren offen sind?

**Comment by mdaudi1982** [comment]
Ich habe es jetzt tatsächlich so gelöst bekommen. Keine Ahnung, ob das die geschickteste Variante ist, aber es funktioniert.
Danke für deine Hilfe! 

![Blockly](https://user-images.githubusercontent.com/82971021/124567078-ee78c780-de43-11eb-8a30-f1ed865b7d56.jpg)
