### ISSUE TITLE
action xy not successfully set!

### ISSUE THREAD

**Issue by stenmic** [smaragdschlange/ioBroker.nuki#54]
ich habe mit dem Adapter (1.5.0) oft Warnungen im Log.
 ##
![D0EF0BD6-9AD2-4E80-8879-3B40F1625918](https://user-images.githubusercontent.com/56360313/130235566-c753f593-cbe4-4e95-b582-6ec8363e517d.jpeg)

Das war auch schon bei den älteren Versionen.

Meistens werden die Befehle dabei umgesetzt. Manchmal muss ich aber auch 2 oder 3x “pushen“
Das ist übel, wenn man vor der Tür steht 😬

Nun habe ich den ioBroker frisch, mit den neusten Adaptern installiert und auch mal das Schloss und die Bridge auf Werkseinstellungen zurückgesetzt.

Brachte leider keine Besserung.

**Comment by smaragdschlange** [comment]
Hi,
die Meldung kommt, wenn die Nuki Bridge in ihrer Antwort keine Erfolgsmeldung zurück gibt. Das geschieht, wenn die Bridge den Befehl erhalten und an das Lock gesendet hat, das Lock aber den Befehl noch nicht ausgeführt hat. Kann sein, dass der Befehl in einer Warteschlange steckt und das Nuki Lock dann doch noch reagiert. Da kann ich nicht wirklich was machen. In meiner Installation beobachte ich diese Warnungen bislang nicht. Könnte die Verbindung zwischen Nuki Lock und Bridge evtl. gestört oder schwach sein? Vielleicht könntest Du mal versuchen, die Bridge näher an das Lock aufzustellen.
Dass ich manchmal "pushen" muss, habe ich auch. Das liegt aber bei mir daran, dass das Lock gerade kurz vorher einen Zustand gemeldet hat (z.B. Tür geschlossen oder Schloss verriegelt). Dann braucht die Bridge eine kleine Weile, bis sie wieder Befehle entgegennehmen kann. Da hilft nur Geduld. 
Ob dies bei Deinen beschriebenen Fällen auch so abgelaufen ist, weiß ich nicht, ist aber meine Vermutung...

Ich werde mal sehen, ob ich eine automatische Wiederholung von nicht ausgeführten Befehlen einbauen kann oder eine zusätzliche Statusabfrage, bevor ich die Warnmeldung schreibe.

Gruß
Sven

**Comment by stenmic** [comment]
ok, ist zwar komisch, da die Bridge nur 1m vom Schloss angebracht ist.
Welche Einstellung verwendest du beim Energiesparmodus. Ich hab da automatisch stehen. Was bedeutet eigentlich die Option „einfachen Token erzwingen“ im Adapter?

**Comment by smaragdschlange** [comment]
Hi,
hm, dann hat das wahrscheinlich noch eine andere Ursache. Ich hab beim Energiesparmodus auch automatisch.
"Einfachen Token erzwingen" unterdrückt lediglich die Verwendung eines Hash-Wertes bei der Kommunikation mit der Bridge/ dem Nuki. Der Token wird dann im Klartext übertragen.

Gruß
Sven

**Comment by iobFan** [comment]
seitdem ich meinen raspberrypi auf die neueste nodejs & npm version gebracht habe, bekomme ich auch dauernd "status not successfully set" meldungen:


2022-06-24 07:27:26.924  - warn: nuki.0 (27819) action 1 not successfully set!
2022-06-24 12:45:37.921  - warn: nuki.0 (27819) action 2 not successfully set!
2022-06-24 17:26:29.896  - warn: nuki.0 (27819) action 2 not successfully set!
2022-06-24 18:36:12.775  - info: nuki.0 (27819) action 3 set successfully

Versionen: 

/usr/bin/node
v16.15.1
/usr/bin/npm
8.12.2

**Comment by iobFan** [comment]
Hallo @smaragdschlange, könntest du dir das bitte nochmal anschauen? Re-open
