### ISSUE TITLE
Nuki 3.0 

### ISSUE THREAD

**Issue by exitus27** [smaragdschlange/ioBroker.nuki#56]
I have the new nuki 3.0, it is integrated but the data is missing

**Comment by smaragdschlange** [comment]
Hi,
which version of the adapter do you have installed? Are there any error messages? Please provide your ioBroker logfile with nuki messages.

**Comment by exitus27** [comment]
`<html>
<body>


nuki.0 | PID | Zeit | debug | Nachricht
-- | -- | -- | -- | --
nuki.0 | 1639 | 2021-12-05 13:03:42.559 | debug | stateChange nuki.0.616124045.actions.action {"val":0,"ack":true,"ts":164582616352555,"q":0,"from":"system.adapter.nuki.0","user":"system.user.admin","lc":16245456484119}
nuki.0 | 1639 | 2021-12-05 13:03:42.451 | debug | Callback list requested: http://192.168.10.180:9191/callback/list?&ts=2021-12-05T12:03:42Z&rnr=62661&hash=03bb75432bf286d7ac06d9207c08225aa073bda80c1c46391cd4f
nuki.0 | 1639 | 2021-12-05 13:03:39.607 | debug | stateChange nuki.0.7354548.info.batteryCritical {"val":false,"ack":true,"ts":163845465573,"q":0,"from":"system.adapter.nuki.0","user":"system.user.admin","lc":1636465565252}
nuki.0 | 1639 | 2021-12-05 13:03:39.602 | debug | stateChange nuki.0.65515165.actions.lockAction {"val":true,"ack":true,"ts":1638705819571,"q":0,"from":"system.adapter.nuki.0","user":"system.user.admin","lc":163793345560}
nuki.0 | 1639 | 2021-12-05 13:03:39.573 | debug | stateChange nuki.0.6155605.info.keypadBatteryCritical {"val":false,"ack":true,"ts":1638705819546,"q":0,"from":"system.adapter.nuki.0","user":"system.user.admin","lc":1626556461663}
nuki.0 | 1639 | 2021-12-05 13:03:39.566 | debug | stateChange nuki.0.6114045.info.batteryCritical {"val":false,"ack":true,"ts":1638705819546,"q":0,"from":"system.adapter.nuki.0","user":"system.user.admin","lc":16265651321663}
nuki.0 | 1639 | 2021-12-05 13:03:39.522 | error | Unknown device type (4). Setting minimal states.
nuki.0 | 1639 | 2021-12-05 13:03:39.521 | debug | found Nuki device: 734845468
nuki.0 | 1639 | 2021-12-05 13:03:39.515 | debug | found Nuki device: 651513665


</body>
</html>`

**Comment by smaragdschlange** [comment]
I have just updated the adapter to version 1.6.0 which should support the new devices (Nuki 3.0 and Smart Door). 
Please install this version from GitHub and test. I would appreciate your feedback since I do not own any of the new devices.

**Comment by exitus27** [comment]
After updating to 1.6.0 it works thanks
