### ISSUE TITLE
Usage of Nuki 3.0 pro with your adapter

### ISSUE THREAD

**Issue by jayfizzle** [smaragdschlange/ioBroker.nuki#57]
hi,
thanks for your work on the nuki adapter and for adding support for nuki 3.0 (pro).
I have some questions about the integration of nuki 3.0 (pro), it's not a bug report, i need just further information.

The adapter settings currently need the following information:
- ip address of the nuki bridge
- port of the nuki bridge
- token of the nuki bridge

![grafik](https://user-images.githubusercontent.com/40118991/145203051-48b319d8-f10a-423b-afad-3e1985549952.png)

As a nuki 3.0 pro user, where do i get the needed information for the adapter because there is no bridge included/in use.
Can i use the ip/port of the nuki itself?
How can i get the needed token, if the token is really required

kind regards
j.

**Comment by smaragdschlange** [comment]
Hi,
unfortunately I do not own a Nuki 3.0 pro (yet), but from the API and from what I read so far it is my understanding, that the Wifi module inside the SmartLock replaces the Nuki bridge. The API is still the same, so I would expect the Nuki ip, port and token to be used in the adapter.
In theory, the token should be provided by the Nuki SmartLock via Nuki app, but that would be a guess.
I'd like to encourage you to test with my adapter and send me the feedback.
Kind regards,
Sven

**Comment by smaragdschlange** [comment]
Hi, again,
I just found some information about the new Nuki and the API that is used by my adapter:
https://support.nuki.io/hc/de/articles/4408533438993-Fernzugriff-%C3%BCber-die-Nuki-Bridge
Unfortunately they state that the integrated WiFi module is not compatible with the bridge API. For that you'd still need a Nuki bridge 😕

**Comment by jayfizzle** [comment]
hi,
thanks, what i understand is that there is currently no special API for the pro version.
So i don't understand why i should prefer the pro version instead of the no pro version.

I already ordered the pro, i will check how noisy it is and will maybe send it back and changed it with the no pro version.

**Comment by smaragdschlange** [comment]
I guess the Nuki 3.0 pro might be usable without the bridge if you use the WebAPI. Just not with this adapter, yet.
Sorry.
