### ISSUE TITLE
feature for activating and deactivating auto unlock

### ISSUE THREAD

**Issue by mcbirne** [smaragdschlange/ioBroker.nuki#58]
Is it possible to add the feature for activating an deactivating die auto unlock.
that would be very helpful.

**Comment by smaragdschlange** [comment]
Hi,
yes, I see that this would be a cool feature. But since this adapter is using the Nuki bridge API only, it cannot be added unless the API provides this feature. Currently, the only lock actions that can be sent are:

unlock
lock
unlatch
lock ‘n’ go
lock ‘n’ go with unlatch

Regards
Sven
