### ISSUE TITLE
Material and other compatible states

### ISSUE THREAD

**Issue by GermanBluefox** [smaragdschlange/ioBroker.nuki#6]
Can you provide standard states that can be detected by material and other adapters?

https://github.com/ioBroker/ioBroker/blob/master/doc/STATE_ROLES.md#sensor-booleans-read-only
Role: sensor.lock.door (type=boolean, write - false, false - closed, true - opened)
Role: switch.lock.door (type=boolean, write - true, false - close, true - open)
Role: button.open (type=button, type=boolean, write - true, read - false, true - unlatch)

**Comment by smaragdschlange** [comment]
Hi,
sure, will do.

Gruß,
Sven

**Comment by smaragdschlange** [comment]
Hi there,
I was working on callback functionality which is not completed, yet. But the states are now adjusted as requested.
Again, thanks for the advice.

Gruß,
Sven
