### ISSUE TITLE
hasOwnProperty fatal error

### ISSUE THREAD

**Issue by krobipd** [smaragdschlange/ioBroker.nuki#60]
Hallo,

habe gerade die aktuelle Version deines Adapters installiert und bekomme Immer den folgenden Fatal Error
`

nuki.0 | 2021-12-29 01:06:51.366 | error | Cannot read property 'hasOwnProperty' of undefined
-- | -- | -- | --
nuki.0 | 2021-12-29 01:06:51.366 | error | TypeError: Cannot read property 'hasOwnProperty' of undefined at initNukiDeviceStates (/opt/iobroker/node_modules/iobroker.nuki/main.js:374:19) at updateAllLockStates (/opt/iobroker/node_modules/iobroker.nuki/main.js:883:17) at Request._callback (/opt/iobroker/node_modules/iobroker.nuki/main.js:1257:17) at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22) at Request.emit (events.js:400:28) at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1154:10) at Request.emit (events.js:400:28) at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/request/request.js:1076:12) at Object.onceWrapper (events.js:519:28) at IncomingMessage.emit (events.js:412:35)
nuki.0 | 2021-12-29 01:06:51.365 | error | uncaught exception: Cannot read property 'hasOwnProperty' of undefined

`

Node.js:
v14.18.2
NPM:
6.14.15

**Comment by smaragdschlange** [comment]
Hallo,
ich seh mir das mal an. Bitte beantworte mir dazu noch folgende Fragen: 
Welche Nuki-Geräte (Nuki Lock 1.0/2.0/3.0, Nuki Bridge/Software Bridge, Nuki Opener etc.) hast Du denn? Hast Du den Token im Adapter eingetragen? Funktioniert das Schloss über die Nuki App auch remote, wenn keine Bluetooth-Verbindung mit dem Handy besteht?

Gruß Sven

**Comment by krobipd** [comment]
Hallo

ist ein Nuki 2 mit Hardware Bridge.
Ja habe den Token eingetragen.
Oh bzgl aus der Ferne öffnen, muss ich mal probieren 🙈

**Comment by smaragdschlange** [comment]
Hi,
kann es sein, dass Du das Nuki Lock noch nicht vorher benutzt hattest, als Du den Adapter installiert hast?

**Comment by krobipd** [comment]
Das Schloss mit Bridge laufen eigentlich schon seit Jahren. Hatte auch mal den extended Adapter laufen aber da das ganze nicht so zufriedenstellend war hatte ich das aufgehört. Jetzt wollte ich das ganze noch mal aus probieren. Die Bridge hat jedenfalls Firmware Version 2.10.4.

**Comment by smaragdschlange** [comment]
Hm, FW kan es also nicht sein...
Ist die API auf der Bridge aktiviert?

**Comment by krobipd** [comment]
Serwus

danke für deinen flotten support und sorry für die späte Antwort.
jedenfalls ja es ist alles aktiviert, hatte schonmal beide adapter ausprobiert.

jedenfalls habe ich die bridge jetzt wo anders hingetan und schwups funktioniert alles wunderbar.
hatte nämlich auch immer wieder mega Verbindungsprobleme mit meinen unifi Wlan Access Points - Ticket bei Nuki ist schon offen - und das obwohl andere Geräte daneben normal Funktionieren.

Im Moment funktioniert die Bridge also an Ihrer neuen Position einwandfrei - kein reconnect Problem, Fernwartung (das bedienen aus der Ferne via App) und Adapter funktionieren jetzt.

**Comment by smaragdschlange** [comment]
Das freut mich, dass es jetzt funktioniert.

Gruß Sven
