### ISSUE TITLE
Exception-Code: EADDRINUSE: listen EADDRINUSE: address already in use 192.168.X.XX:9092

### ISSUE THREAD

**Issue by skyx3** [smaragdschlange/ioBroker.nuki#66]
Erstmal vielen Dank für den tollen Adapter! :-)

Ich habe zwei Nuki Bridges (weil das zweite Schloss zu weit entfernt ist von Bridge 1), beim einrichten der zweiten Bridge kommt jetzt aber immer der Fehler: "Exception-Code: EADDRINUSE: listen EADDRINUSE: address already in use 192.168.X.XX:9092". Ich verstehe soweit das anscheinend nicht zwei Nuki Bridges gleichzeitig auf einen Port zugreifen können, aber kann ich denn weitere abweichend Callback Ports einrichten? Über Google bin ich hier leider nicht fündig geworden.

**Comment by smaragdschlange** [comment]
Hi,
vielen Dank.
Ich bin mir nicht ganz sicher, ob ich das Problem verstanden hab. Zunächst mal: Haben alle drei Geräte (Nuki Bridge 1, Nuki Bridge 2 und ioBroker) unterschiedliche IP-Adressen? Wenn das gegeben ist, solltest Du folgendermaßen vorgehen:
Für jede Nuki Bridge benötigst Du eine eigene Adapterinstanz. In jeder Adapterinstanz legst Du einen eigenen, unbenutzten Port fest. Der Port muss unterschiedlich sein, weil sonst die Zuordnung nich funktioniert. Wenn Du weiterhin die Fehlermeldung bekommst, probiere einen anderen Port. Überprüfe auch im Browser mal die Callbacks, die bereits auf den Bridges eingerichtet sind.

Ich hoffe,  das hilft Dir weiter.

Gruß Sven

**Comment by skyx3** [comment]
Hi, ja war etwas zu ungenau beschrieben. Es ist alles wie bschrieben eingerichtet. Ich habe jetzt zum testen bei dem zweiten Adapter den Port auf 9093 angepasst und es scheint zu gehen, nur weiß ich nicht ob ich mir hier einfach Ports ausdenken kann. Ich bin bisher davon ausgegangen das jeder Port seine eigene Funktion hat und man nicht einfach irgend eine Portnummer nehmen kann.

**Comment by skyx3** [comment]
Vielen Dank, aber muss auf der anderen Seite des Ports nicht auch jemand auf Feedback warten? Oder sagt der Nuki Adapter der Nuki Bridge ich lausche jetzt auf 9093? Und die Nuki Bridge antwortet dann auf die 9093? Sorry für die blöde Frage :-)

**Comment by smaragdschlange** [comment]
Der im Adapter einstellbare Port ist nur für den Callback, also die Adresse, an die die Bridge eine Statusänderung meldet. Für Befehle vom Adapter an die Bridge/das Nuki Smartlock wird eine REST-API (über http) verwendet. Die Angabe eines Ports ist dafür nicht erforderlich und eine Änderung des Ports nicht vorgesehen.
