### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by actionbyte** [smaragdschlange/ioBroker.nuki#67]
Hi,

seit kurzem kann ich nicht mehr über die Bridge den Status meiner 3 Nuki-Schlösser auslesen oder steuern.
Im Protokoll erscheint ständig: 
`<html><body>

nuki.0 | 2022-05-15 11:22:15.845 | error | Error: read ECONNRESET
-- | -- | -- | --
nuki.0 | 2022-05-15 11:22:12.851 | error | Error: read ECONNRESET
nuki.0 | 2022-05-15 11:22:09.853 | error | Error: connect ECONNRESET 192.168.1.9:8080

</body>
</html>`

IP, Port und Token der Bridge sind korrekt. Instanz vom Adapter ist auf "grün", was kann ich zur Analyse noch einstellen.
Es funktionierte alles einwandfrei, ich kann i.M. nicht sagen warum nun nicht mehr.
Wo liegt mein Fehler?

**Comment by smaragdschlange** [comment]
Was geben denn die folgenden URLs im Browser zurück (<token> durch Deinen Token ersetzen):
http://192.168.1.9:8080/callback/list?token=<token>
http://192.168.1.9:8080/info?token=<token>

Gruß
Sven

**Comment by actionbyte** [comment]
Das Problem hat sich schon seit längerem erldigt und lag nicht am Adapter.
Ich habe die Schlösser von der Bridge wieder egtrennt und alles zurück gesetzt.
Danach alle i.O.
Soweit ich noch weiß war es ein Fehler der Bridge trotz der fehlerhafte Verbindung keinen konkreten Fehler angezeigt zu haben.
