### ISSUE TITLE
warn .info.keypadBatteryCritical

### ISSUE THREAD

**Issue by Brainbug01** [smaragdschlange/ioBroker.nuki#68]
Meldung im Log, bin mit allem up-to-date auf latest.

```
nuki.0
2022-06-11 06:47:04.018	warn	State "nuki.0.xxxxxxxx.info.keypadBatteryCritical" has no existing object, this might lead to an error in future versions
```

**Comment by smaragdschlange** [comment]
Die Meldung kommt meiner Erfahrung nach nur beim ersten Start des Adapters bzw. bei der Erzeugung eines neuen Objektknotens. Im laufenden Betrieb sollte die Meldung nicht mehr auftauchen und hat auch keinen Einfluss auf die Funktion des Adapters.

Gruß
Sven

**Comment by Brainbug01** [comment]
Ja ich sehe die Meldung nicht standig. Ist auch kein wirkliches Problem des Adapters! Der läuft einfach top!
