### ISSUE TITLE
Protokoll

### ISSUE THREAD

**Issue by Instanz1** [smaragdschlange/ioBroker.nuki#69]
Ich weiß nicht ob es möglich ist, aber gibt es die Möglichkeit ein Protokoll zu sehen wann wer die Tür geöffnet hat?

Gruß

**Comment by smaragdschlange** [comment]
Ein solches Protokoll wird von der Brigde-API nicht angeboten. Das geht nur über die Web-API, die ist aber in diesem Adapter (absichtlich) nicht integriert.

Gruß
Sven
