### ISSUE TITLE
Please add standard github based testing

### ISSUE THREAD

**Issue by mcm1957** [smaragdschlange/ioBroker.nuki#75]
This adapter seems to be missing standard GITHUB based testing unsing @iuobroker.testing. This is required for the adapter to be updated at repositories.

Standard testsing can be found at iobroker.example or at any upd to date adapter<
I can supply a PR if desired. Please let me know.

If you do not have time to maintain this adapter any longer, please drop a note so that we can find a solution.

**Comment by simatec** [comment]
I have made a PR on the known problems... Let's see if the developer releases it...
https://github.com/smaragdschlange/ioBroker.nuki/pull/78

**Comment by smaragdschlange** [comment]
Hi,
thanks to the fixes by @simatec standard GITHUB based testing has been added to version 2.0.0.

Regards
Sven
