### ISSUE TITLE
Auslesen des Token über Browser nicht möglich. (Kein Bug im Adapter)

### ISSUE THREAD

**Issue by winni-priel** [smaragdschlange/ioBroker.nuki#83]
**Describe the bug**  
Das Auslesen des Tokens mittels http://<Nuki Bridge IP>:8080/auth hat bei mir nicht funktioniert, getestet mit Chrome, Firefox und Opera über ein Android Tablett. Z.B. die Fehlermeldung von Firefox: 

"Sichere Verbindung fehlgeschlagen

    Die Webseite kann nicht angezeigt werden, da die Authentizität der erhaltenen Daten nicht verifiziert werden konnte.
    Kontaktieren Sie bitte den Inhaber der Website, um ihn über dieses Problem zu informieren."

Über die Nuki-App funktioniert es aber. Vielleicht kann das noch jemand verifizieren und gegebenenfalls das Redme ändern. 
Danke

**Comment by Horgul123** [comment]
Mit Bridge getestet, keine Probleme

**Comment by winni-priel** [comment]
Danke für den Test. Ich habe es jetzt nochmal mit meinem Handy probiert, damit hat es funktioniert. Schein also irgendwie an dem Tablett zu liegen.
