### ISSUE TITLE
nach update auf 2.0.0 nicht mehr steuerbar über ioBroker VIS

### ISSUE THREAD

**Issue by darkblu23** [smaragdschlange/ioBroker.nuki#84]
ich habe die Datenpunkte (Objekte) in der VIS eingebunden und konnte so
das NUKI aufschliessen, abschliessen oder die Tür öffnen lassen.

Nach update auf 2.0.0 funktioniert das nicht mehr.

Bediene ich das NUKI per Handy, werden alle Befehle ausgeführt, aber in den Objekten ändert sich nix.

Ich bin dann wieder zurück auf 1.6.0. Hab aber nicht drauf geachtet was vorher installiert war.
1.7.0 wird zwar angeboten, ist aber scheinbar nicht (mehr) vorhanden.
Jetzt funktioniert alles wieder tadellos, also mit 1.6.0

**Versions:**  
 - Adapter version: <2.0.0>
 - JS-Controller version: <5.0.19>
 - Node version: <18.20.3> 
 - Operating system: <Bookworm>

**Comment by ELK169** [comment]
bei mir ebenso. Im Log sah ich, dass der Token falsch sein solle. Daraufhin habe ich in der Nuki-App nachgesehen und dort einen anderen API-Token gesehen, den ich dann in den Adaptereinstellungen eingetragen habe. Seitdem kommt sie Meldung über den falschen Token nicht mehr, funktionieren tut es aber trotzdem nicht.

**Comment by ELK169** [comment]
PS: nachdem ich Version 1.6 installierte und die Einstellungen dann nicht mehr aufrufbar waren habe ich 2.0 wieder installiert. Jetzt funktioniert alles. Sehr seltsam!

**Comment by darkblu23** [comment]
PS:
nach update auf 2.0.0 muss in der Instanz der Token (aus der Bridge) neu eingetragen werden.
Gesagt, getan - nun läuft es wieder perfekt.
