### ISSUE TITLE
TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters

### ISSUE THREAD

**Issue by RedondoBoony** [smaragdschlange/ioBroker.nuki#86]
**Describe the bug**  
I get the following error after updating the Adapter and running it:
(every 3 seconds)
**TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters**

**Versions:**  
 - Adapter version: v2.0.0
 - Node version: v18.20.3
 - Operating system: Docker Image

Worked before

**Comment by mcm1957** [comment]
Please add version of admin and js-controller.
Please add complete log.

**Comment by RedondoBoony** [comment]
Sorry it has been solved. Somehow after an update the token had been stored cryptically...
