### ISSUE TITLE
Connection to NUKI bridge dont work anymore

### ISSUE THREAD

**Issue by Harry423** [smaragdschlange/ioBroker.nuki#87]
**Describe the bug**  
After updating adapter to version 2.0 the connection to NUKI bridge dont work anymore. The error "Invalid toke given" appears. After five errors the adapter stop to work

**To Reproduce**  
1. Adapater deinstalled
2. Adapter new installed from repository
3. New token gerenated in NUKI web portal.
4. Tried both tokens - same result

**Expected behavior**  
Adapter should run like bevor the update

**Screenshots & Logfiles**  
![Bildschirmfoto 2024-06-29 um 17 34 55](https://github.com/smaragdschlange/ioBroker.nuki/assets/73777886/8b5d068a-9a0a-42f5-820b-51c1b026cf30)

![Bildschirmfoto 2024-06-29 um 17 35 18](https://github.com/smaragdschlange/ioBroker.nuki/assets/73777886/50e12685-d7c7-4273-8cf9-82dafcd1ab3c)

**Versions:**  
 - Adapter version: 2.0.0
 - JS-Controller version: 5.0.19
 - Node version: 18.20.3
 - Operating system: debian bookworm

**Comment by mcm1957** [comment]
Please reenter your token ONCE after updating to V2.0.0.
Due to encryption changes enterng the token again is required.

**Comment by Harry423** [comment]
Hello,

thank you for the quick feedback. 

I've entered the old token four times and also create a new token and enter this token too.

Nothing works :-(

**Comment by mcm1957** [comment]
Ok, sorry - Then I do not know a solution. Lets wait for @smaragdschlange.
In most cases the missing info to reenter token is the reason for this problem.

In addtion I would suggest to post you problem at the nuki topic in the forum too. Maybe someone there has an idea what could be wrong.

**Comment by smaragdschlange** [comment]
Hi,
I faced the same issue after updating. I'm not sure what exactly fixed it for me, but I've set the "Einfachen Token erzwingen" (force simple token) flag and saved. Afterwards I've unchecked that flag again and saved again.
If this doesn't work, I'd recommend to try to uninstall the adapter and reinstall it again (remember your settings before uninstalling).

I hope this works for you.

Regards
Sven

**Comment by Harry423** [comment]
Sorry this is what i did before open the issue.  ;-) 

![Bildschirmfoto 2024-07-10 um 19 01 19](https://github.com/smaragdschlange/ioBroker.nuki/assets/73777886/1a4c1c05-1646-4014-869f-e30227c90da3)

I've deinstalled the plugin and loaded it new from scratch. The enabling of "simple token" is the first what I did.
I've tried both variants with and without enabling this feature. I see that the hash is different but the error not.
Nothing of them helps unfortunately. 

What's really wondering me is: I've tried to install the old version (1.6.0) but the error stays?! 
A rollback might be no solution.

**Comment by smaragdschlange** [comment]
May I ask why you don't use the callback?

**Comment by Harry423** [comment]
Good question ;-)

but it make no difference...

![Bildschirmfoto 2024-07-10 um 19 18 53](https://github.com/smaragdschlange/ioBroker.nuki/assets/73777886/9a7727fb-5057-4d99-be0d-06ca95adea1d)

**Comment by smaragdschlange** [comment]
What happens when you connect to the bridge via browser? E.g. type into your browser http://192.168.178.XXX:8080/callback/list?token=XXXXXX (with your NUKI-bridge ip and token)?

**Comment by Harry423** [comment]
an error occurs:

![Bildschirmfoto 2024-07-10 um 19 39 51](https://github.com/smaragdschlange/ioBroker.nuki/assets/73777886/d38fbf29-1605-4e8c-8aa0-6c0e24d2505e)

**Comment by Harry423** [comment]
I also have plugged out the bridge and plugged it in again. --> The some error happens.
At the webpage the bridge is working well:

![Bildschirmfoto 2024-07-10 um 19 46 39](https://github.com/smaragdschlange/ioBroker.nuki/assets/73777886/1bd7be05-1b1f-4a07-a0b0-04a13f53c320)

**Comment by smaragdschlange** [comment]
Hi,
the link I asked you to set in your browser is a direct connection to your NUKI-bridge (without ioBroker or my adapter). So, if the link does not give you the callback-list but HTTP-code 401 instead, you are actually using an incorrect token or your bridge is currently not set up for API calls. Please try to follow the instructions in chapter 3.1 of the bridge API manual:
https://developer.nuki.io/page/nuki-bridge-http-api-1-13/4/

Regards
Sven

**Comment by Harry423** [comment]
Hello,
this documentation solves the problem now.
What I don’t understand is that since to the update the original token generated from the website don’t work anymore.

But in the end it works…

Thank you for your support...

**Comment by smaragdschlange** [comment]
Hi,
I'm glad it worked.

Regards
Sven
