### ISSUE TITLE
Software bridge & "null" device

### ISSUE THREAD

**Issue by Zefau** [smaragdschlange/ioBroker.nuki#9]
Thanks for your development. I would like to support you if you need help with the development. I developed a nello adapter not too long ago (https://github.com/Zefau/ioBroker.nello).

I experienced two issues:
1. The adapter creates a tree `null` (`nuki.0.null.35...669`). 
2. I'm using a software bridge (running an android app, see https://nuki.io/de/blog-de/android-bridge-app-2/). Due to this, the API apparently does not publish an IP address for some reason. The URL https://api.nuki.io/discover/bridges only returns `bridgeId`, `dateUpdated` and `errorCode`. So https://github.com/smaragdschlange/ioBroker.nuki/blob/master/main.js#L514 returns `false` and `initBridgeStates` will not be called for me.

Furthermore, I found a nuki API implementation on npm (https://www.npmjs.com/package/nuki-api) and was wondering why the adapter is not based on the API implementation?

Cheers,
Zefau

**Comment by smaragdschlange** [comment]
Hi Zefau,
the issue, that a software bridge is not created as an object in ioBroker because it doesn't return an ip address has been fixed.
I think the first issue has been a follow up error because I never experienced it in my installation.

Greetings,
Sven
