### ISSUE TITLE
Nuki Smart Lock 4.0 ... 

### ISSUE THREAD

**Issue by RoboCop0815** [smaragdschlange/ioBroker.nuki#91]
... benötige ich um den Adapter nutzen zu können auch noch eine Nuki Bridge oder reicht das Nuki Smart Lock 4.0 und wenn ja wie?

**Comment by smaragdschlange** [comment]
Hi,
es wird eine Bridge benötigt. Entweder eine originale NUKI-Bridge oder eine Software-Bridge auf einem (alten) Handy.

Gruß
Sven

**Comment by RoboCop0815** [comment]
> Hi, es wird eine Bridge benötigt. Entweder eine originale NUKI-Bridge oder eine Software-Bridge auf einem (alten) Handy.

Ich habe das Nuki 4 Pro mit integrierten WLAN, wie sieht es damit aus? habe ja eine IP Adresse
