### ISSUE TITLE
Connection to bridge does not work anymore

### ISSUE THREAD

**Issue by LoneWolf-83** [smaragdschlange/ioBroker.nuki#92]
Since upgrading to 2.0 I get this in the logs:

![image](https://github.com/smaragdschlange/ioBroker.nuki/assets/67790431/c11455c7-be0e-41b7-9df8-2f9ac2e797cc)

In 1.6 everything was fine.

However in the browser all looks good besides the strange name for the device:

[{"deviceType": 2, "nukiId": 860981970, "name": "��������������������������������G", "firmwareVersion": "1.10.1", "lastKnownState": {"mode": 2, "state": 1, "stateName": "online", "batteryCritical": false, "keypadBatteryCritical": false, "timestamp": "2024-07-08T13:30:14+00:00"}}]

Versions:

node: v20.11.1
npm: 10.2.4

Please help.

And please maintain the old versions in iobroker - currently I'm not able to downgrade.

**Comment by mcm1957** [comment]
Older versions are always available at npm. Theres no spezialisiert maintainance for this 

As you do not state what problems you have doing downgrade I cannot advise further. In addition I suggest to ask at forum if problems downgraden as this will reach more problems to help.

**Comment by LoneWolf-83** [comment]
Thanks, I just noticed that I cant downgrade using the iobroker UI.
I will give the npm downgrade a try.

**Comment by mcm1957** [comment]
Simply use expert Mode and iE specify nuki@1.2.3 as url.

Do NOT use nmp i ... to install.

**Comment by LoneWolf-83** [comment]
So it seems like the same happens with the 1.6.0 version of the adapter.
It seems like my strange Opener Name might cause this issue - i will check with Nuki support.
Therefore I will close this.
